.PHONY: all
all:
	@echo "AVAILABLE TARGETS\n"
	@echo "milestonecontrol:      run milestone control test gui"
	@echo "milestonecontrol_auto: run milestone control test sequence"

.PHONY: milestonecontrol
milestonecontrol:
	/usr/bin/env python3 milestonecontrol/run.py --gui

.PHONY: milestonecontrol_auto
milestonecontrol_auto:
	/usr/bin/env python3 milestonecontrol/run.py --auto


