.PHONY: all
all:
	@echo "AVAILABLE TARGETS\n"
	@echo "msctl:      run milestone control test gui"
	@echo "msctl_auto: run milestone control test sequence"

.PHONY: msctl
msctl:
	/usr/bin/env python3 milestonectrl/run.py --gui

.PHONY: msctl_auto
msctl_auto:
	/usr/bin/env python3 milestonectrl/run.py --auto


